backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "homepage"
    label: "Contenu du site"
    file: "content/homepage.json"
    fields:
      - { label: "Nom", name: "name", widget: "string" }
      - { label: "Titre", name: "job_title", widget: "string" }
      - { label: "Sous-titre", name: "subtitle", widget: "string" }
      - { label: "Objectif", name: "objective", widget: "text" }

      - label: "Photo de Profil"
        name: "profile_image"
        widget: "image"
      
      - label: "Compétences Techniques"
        name: "skills_hard"
        widget: "list"
        field: { label: "Skill", name: "skill", widget: "string" }

      - label: "Compétences Soft"
        name: "skills_soft"
        widget: "list"
        field: { label: "Skill", name: "skill", widget: "string" }

      - label: "Expériences"
        name: "experience"
        widget: "list"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Années", name: "years", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }

      - label: "Formation"
        name: "education"
        widget: "list"
        fields:
          - { label: "École", name: "school", widget: "string" }
          - { label: "Années", name: "years", widget: "string" }
          - { label: "Ville", name: "city", widget: "string" }

      - label: "Contact"
        name: "contact"
        widget: "object"
        fields:
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Téléphone", name: "phone", widget: "string" }
          - { label: "Localisation", name: "location", widget: "string" }
